openapi: 3.0.3
info:
  title: QRNotfy-Admin
  description: proyecto back test para qrnotify
  version: 1.0.0
servers:
  - url: '{protocol}://nebrija-tfg/{basePath}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
        description: This value is assigned by the transfer protocol that has to be used
      basePath:
        default: /clients/qrnotify
tags:
  - name: Test
    description: Testing service
  - name: User
    description: Everything about users
  - name: Admin
    description: Admin controller
paths:
  /test:
    get:
      tags:
        - Test
      summary: Prueba test
      description: Prueba test
      operationId: test
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/general_response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '405':
          description: Method call not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '500':
          description: Internal Server Error QRNotify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '503':
          description: Internal QRNotify storage system error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
components:
  schemas:
    general_response:
      title: object of general response
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
          description: Service return codigo.
        message:
          type: string
          description: Description of the result of the operation performed
    error:
      title: Error en la aplicacion
      required:
        - code
        - message
        - request_id
      type: object
      properties:
        code:
          type: string
          description: Codigo del resultado erroneo
        message:
          type: string
          description: Descripcion del resultado erroneo
        request_id:
          type: string
          description: Codigo de peticion unico.
        details:
          type: object
          properties: { }
          description: objeto con el detalle adicional de errores que desee aportar
    error_response:
      title: Error en la aplicacion encapsulado
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/error'
    permission_request_dto:
      type: object
      properties:
        topic_id:
          type: string
          example: "123456789"
    permission_response_dto:
      type: object
      properties:
        topic_id:
          type: string
          description: "id of the topic"
          example: "123456789"
        active:
          type: boolean
          example: true
    user_response_dto:
      type: object
      properties:
        name:
          type: string
          example: theUser
        phone_number:
          type: string
          example: '12345'
        created_date:
          type: string
        modificatied_date:
          type: string
        deleted_date:
          type: string
    user_request_dto:
      type: object
      properties:
        name:
          type: string
          example: "hao"
        phone_number:
          type: string
          example: '615656320'
    verify_request_dto:
      type: object
      properties:
        name:
          type: string
          example: "hao"
        phone_number:
          type: string
          example: '615656320'
        code:
          type: string
          example: '123456'
    token_response_dto:
      type: object
      properties:
        token:
          type: string
          example: "123456789"
    admin_response_dto:
      type: object
      properties:
        id:
          type: string
          description: "id of the admin"
          example: "123456789"
        name:
          type: string
          description: "name of the admin"
          example: "Jhon"
        email:
          type: string
          description: "admin email"
          example: "john@email.com"
        permissions:
          type: array
          description: "permissions of areas"
          items:
            $ref: '#/components/schemas/permission_response_dto'
        created_date:
          type: string
        modificated_date:
          type: string
        deleted_date:
          type: string
    admin_request_dto:
      type: object
      properties:
        name:
          type: string
          description: "name of the admin"
          example: "Jhon"
        email:
          type: string
          description: "email"
          example: "john@email.com"
        password:
          type: string
          description: "password"
          example: "1234567"
    update_admin_request_dto:
      type: object
      properties:
        name:
          type: string
          description: "name of the admin"
          example: "Jhon"
        password:
          type: string
          description: "password"
          example: "1234567"
    error_dto:
      title: DTO Error
      type: object
      properties:
        message:
          type: string
        request_id:
          type: string
        details:
          type: string
        code:
          type: string
  responses:
    '200':
      description: successful operation
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/general_response'
    '400':
      description: There was something wrong in the request and therefore could not be processed (headers, json syntax/content)
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/error_response'
    '404':
      description: The server can not find the requested
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/error_response'
    '500':
      description: Unknown Internal server error
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/error_response'
    '501':
      description: The request was not completed. The server did not support the functionality required
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/error_response'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT