openapi: 3.0.3
info:
  title: QRNotfy-Admin
  description: proyecto back test para qrnotify
  version: 1.0.0
servers:
  - url: '{protocol}://nebrija-tfg/{basePath}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
        description: This value is assigned by the transfer protocol that has to be used
      basePath:
        default: /clients/qrnotify
tags:
  - name: Test
    description: Testing service
  - name: User
    description: Everything about users
  - name: Admin
    description: Admin controller
paths:
  /test:
    get:
      tags:
        - Test
      summary: Prueba test
      description: Prueba test
      operationId: test
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/general_response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '405':
          description: Method call not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '500':
          description: Internal Server Error QRNotify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '503':
          description: Internal QRNotify storage system error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
  /admin/turn:
    post:
      tags:
        - Admin
      summary: Create turn
      description: Create turn
      operationId: createTurn
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turn_response_dto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '405':
          description: Method call not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '500':
          description: Internal Server Error QRNotify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '503':
          description: Internal QRNotify storage system error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
  /admin/pass-turn:
    post:
      tags:
        - Admin
      summary: Pass turn
      description: Pass turn
      operationId: passTurn
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turn_response_dto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '405':
          description: Method call not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '500':
          description: Internal Server Error QRNotify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '503':
          description: Internal QRNotify storage system error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
  /user/request-turn:
    post:
      tags:
        - User
      summary: Request turn
      description: Request turn
      operationId: requestTurn
      parameters:
        - name: turnId
          in: query
          description: turnId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/client_turn_response_dto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '405':
          description: Method call not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '500':
          description: Internal Server Error QRNotify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '503':
          description: Internal QRNotify storage system error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
  /user/turns:
    get:
      tags:
        - User
      summary: Get turns
      description: Get turns
      operationId: getTurns
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/turn_response_dto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '405':
          description: Method call not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '500':
          description: Internal Server Error QRNotify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '503':
          description: Internal QRNotify storage system error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
  /turn/{turnId}:
    get:
      tags:
        - User
      summary: Get turn
      description: Get turn
      operationId: getTurn
      parameters:
        - name: turnId
          in: path
          description: turnId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/turn_response_dto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '405':
          description: Method call not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '500':
          description: Internal Server Error QRNotify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
        '503':
          description: Internal QRNotify storage system error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_dto'
components:
  schemas:
    general_response:
      title: object of general response
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
          description: Service return codigo.
        message:
          type: string
          description: Description of the result of the operation performed
    error:
      title: Error en la aplicacion
      required:
        - code
        - message
        - request_id
      type: object
      properties:
        code:
          type: string
          description: Codigo del resultado erroneo
        message:
          type: string
          description: Descripcion del resultado erroneo
        request_id:
          type: string
          description: Codigo de peticion unico.
        details:
          type: object
          properties: { }
          description: objeto con el detalle adicional de errores que desee aportar
    error_response:
      title: Error en la aplicacion encapsulado
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/error'
    client_turn_request_dto:
      type: object
      properties:
        username:
          type: string
          example: theUser
        phone:
          type: string
          example: '12345'
        turn_id:
          type: string
          example: '10'
    turn_request_dto:
      type: object
      properties:
        name:
          type: string
          example: theName
    turn_response_dto:
      type: object
      properties:
        id:
          type: string
          example: 10
        name:
          type: string
          example: theNameOfTheTurn
        topic:
          type: string
          example: 10
        estimated_time:
          type: number
          example: '10'
        current_turn:
          type: string
          example: '10'
        turns:
          type: array
          items:
            $ref: '#/components/schemas/client_turn_response_dto'
        created_date:
          type: string
        modificated_date:
          type: string
        deleted_date:
          type: string
        created_by:
          type: string
    client_turn_response_dto:
      type: object
      properties:
        client_id:
          type: string
          example: theTurn
        turn_number:
          type: string
          example: theTurnNumber
        status:
          type: string
          example: theTurnStatus
        created_date:
          type: string
        modificated_date:
          type: string
        deleted_date:
          type: string
    error_dto:
      title: DTO Error
      type: object
      properties:
        message:
          type: string
        request_id:
          type: string
        details:
          type: string
        code:
          type: string
  responses:
    '200':
      description: successful operation
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/general_response'
    '400':
      description: There was something wrong in the request and therefore could not be processed (headers, json syntax/content)
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/error_response'
    '404':
      description: The server can not find the requested
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/error_response'
    '500':
      description: Unknown Internal server error
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/error_response'
    '501':
      description: The request was not completed. The server did not support the functionality required
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/error_response'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT